### ISSUE TITLE
req_soccerseason_leaguetable not contain correct type for table.

### ISSUE THREAD

**Issue by acche** [icedream/go-footballdata#4]
```// Executes the request.
func (r SoccerSeasonLeagueTableRequest) Do() (s SoccerSeason, err error) {
    d, _, err := r.doJson("GET")
    if err != nil {
        return
    }

```
err = d.Decode(&s)
return
```

}

should not be return SoccerSeason,  it not contain any property about score table.

**Comment by acche** [comment]
I find the result in dev branch , when will you merge that to master branch?

**Comment by icedream** [comment]
Hello, sorry for the slightly late response.

Seeing as there hasn't been any new changes in the develop branch recently and a merge is needed to fix a few things, I'll consider merging into master in the next few days. I'll just have to check whether and which things are going to break.

**Comment by acche** [comment]
Thx your reply.

可用于iOS的myMail发送

2016年9月4日 星期日 +0800 19:21 发件人 Carl Kittelberger  notifications@github.com:

**Comment by acche** [comment]
Some Team name and the flag return null value ,will solve it?

**Comment by icedream** [comment]
I'll close this issue for now. Your other issue will be the follow-up for this one as a lot of the documented fields don't match the data the API server actually returns. That needs to be fixed overall.
